### ISSUE TITLE
Repositorio eliminado

### ISSUE THREAD

**Issue by wodim** [TheBronx/shurscript#72]
Si bien este repositorio ya no es útil, me pregunto si esta acción destructiva fue acordada entre los que mantenían el software: https://github.com/TheBronx/shurscript/commit/ac96fe6891276523322fec918afa6e6e05427355

**Comment by TheBronx** [comment]
No, fue una decisión unilateral. 
De todas formas el repo no se ha borrado, ahora está está en gitlab: https://gitlab.com/salvatorelab/shurscript

**Comment by wodim** [comment]
Lo entiendo, pero me ha parecido una desagradable sorpresa el abrir el repositorio (estaba repasando mis favoritos) y encontrármelo así. Estaría bien que alguien con acceso de escritura pudiera deshacer el commit y restaurar el contenido.

**Comment by TheBronx** [comment]
Insisto, el repo está en https://gitlab.com/salvatorelab/shurscript
Puedes clonarlo, hacer un fork, ver los commits o lo que quieras. Sencillamente ya no está en github.

**Comment by wodim** [comment]
De acuerdo. Entendí que, al ser una decisión "unilateral", no todos los autores del software fueron consultados cuando se vandalizó el repositorio. En otras palabras, fue una acción no deseada. De eso es de lo que yo quería advertir con este "issue".

**Comment by TheBronx** [comment]
Ah vale, claro es que no lo he dicho y no es evidente: ese commit es mío :rofl: 
Vamos, que la decisión unilateral fue mía.
Podía haberlo consultado con los compañeros que más contribuyeron, eso es cierto, pero hace años que no mantenemos contacto, el slack que tuvimos hace mucho que se borró y al final el repo está en mi cuenta así que tampoco me compliqué la vida. 
Gracias por el aviso de todas formas :+1:

**Comment by xusoo** [comment]
Por mí no hay problema. Al fin y al cabo el repositorio está en tu cuenta (tal vez debimos haberlo movido en su día a uno propio).

Un saludo.

**Comment by wodim** [comment]
Gracias por vuestras respuestas y comentarios. Y gracias, cómo no, por trabajar en el script.
